version: "3.8"

services:
  frontend:
    image: ${DOCKERHUB_USERNAME}/${FRONT_IMAGE_NAME}:latest
    container_name: settlement-frontend
    ports:
      - "12345:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
    restart: always
